version: '3.9'

services:
  app:
    build: .
    image: canbi4/skywars:v1.0
    ports:
      - "80:80"
    environment:
      - DB_PASSWORD=db_password
      - DB_USER=db_user
      - DB_NAME=db_name
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_name



#  app:
#    build:
#      context: .
#    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
#    restart: always
#
#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    restart: always
